### ISSUE TITLE
Value vw calculation

### ISSUE THREAD

**Issue by kirstenschelper** [Fluiditype/fluiditype#1]
Thanks for sharing your ideas!
Could you perhaps explain the vw value the font-size calculation is based on?
fontSize: calc(12px + 0.698vw)
Why 0.698vw?
Where does the number come from?

Kirsten

**Comment by boriskirov** [comment]
If we agree with the statement that the best font-size for reading is between 14px-16px, the calculation provides a fluid value of 14,2336px for the 320px mobile size (for Iphone5, and we assume this is a minimum, but still give a range if we go even lower on the screen-size, to still keep in the range of the 14px). You can push the calculation to go more for 16px by just changing the vw value to a bit higher. Hope this helps :)
