### ISSUE TITLE
Clamp size to a container instead of the viewport ? 

### ISSUE THREAD

**Issue by aspben** [Fluiditype/fluiditype#3]
Hi, really like your project, it's exactly what i was looking for! 

One thing I think user would like is to have the font size  clamped to an arbitrary container instead of the viewport. This way, one can add [margin: 0 auto ] around the main container without having the font-size overblown on large display. 

Here is an exemple of what i mean: 
https://codepen.io/benasp/pen/qBdRzQW

There is probably room for optimization for sure. What do you think ?

**Comment by heidkaemper** [comment]
CSS min() and max() are not supported in Firefox and some other Browsers. Therefore the codepen example isn't really the way to go, I think.

If you want to set a maximum font size for large screens, you could just use a combination of fluiditype and a css media query. ;-)

**Comment by boriskirov** [comment]
@aspben thank you for your comment, I will be improving the library on the go yes. I will review and see if I can add an maximum font-size for large screens in a smart way.
@Utakka Thank you for the add on
